---
title: "Research Paper Proposal and Annotations"
subtitle: "Due Fri Nov 15; Joseph Sepich (jps6444)"
output:
  pdf_document:
    toc: false
    toc_depth: 2
    number_sections: false
    keep_tex: false
---

# Research Topic

In one of our first lectures we talked about Nicholas Flamel as a counterexample, so this topic relates to our study of witchcraft in the sense that alchemists were essentially doing what some described as magic, but went unpersecuted. He (Flamel) was a manuscript and book seller in Paris along as a scribe, but most noteably he was known as being an alechemist. I found the topic of alchemy particularly interesting as it bears a close remsemblance to chemistry and science, but was also seen in parallel with magical practices. A further reason I found this subject interesting was the mention of Flamel in Harry Potter, a novel about magic and witchcraft, as the discoverer of the philosopher's stone (which grants a person immortality). I am going to examine how the aspect of alchemy helped to foster the foundations of modern day chemistry. Google describes it as "the medieval forerunner of chemistry." 

# Primary Source Description

There are two sources located in the Penn State library system that are of particular note to my topic. The first source is called Das Wesen der Alchemie and it was written by Dr. Ferdinand Maack. As part of a series called the Occult world it describes various "The Essence of Alechemy" which in actuality were various aspects of science at the time. The other primary source of interest is called Witchcraft, Magic, and Alchemy. It was originally written by an occult scholar in the 1931, but the edition I am using is from 1971. This is a good book to look at what alechemy was at the time, since it gives a description of "Operations of Work" and "The Laboratory of Alchemists".

# Research Questions

1. Alchemy is often referred to as the forerunner of chemistry. In what ways has alchemy influenced chemistry?
2. How was alchemy viewed during the prolific scientific revolution in the early 20th century? What are the similarities and differences of alchemy and chemistry?
3. In reference to the Occult World series, what determined alchemy to be a part of this world, but not chemistry?

# Research Title

Chemistry's Alchemical Influences in Early 20th Century Europe

# Sources

## Alchemy Encyclopedia Entry

Golden, Richard M. Encyclopedia of Witchcraft: The Western Tradition. Santa Barbara, Calif: ABC-CLIO, 2006. http://search.ebscohost.com.ezaccess.libraries.psu.edu/login.aspx?direct=true&db=nlebk&AN=148574&site=ehost-live&scope=site

This source is an encyclopedia entry on Alchemy and will help to answer some basic historical questions. It has both what alchemy is and he historical background. These topics are important in answering the first research question about alchemy being a forerunner to chemistry. If I understand what alchemy is then I can better analyze it to understand how it may have evolved into or influenced chemistry.

## Faust, Johann Georg Encyclopedia Entry

Golden, Richard M. Encyclopedia of Witchcraft: The Western Tradition. Santa Barbara, Calif: ABC-CLIO, 2006. http://search.ebscohost.com.ezaccess.libraries.psu.edu/login.aspx?direct=true&db=nlebk&AN=148574&site=ehost-live&scope=site

This is a second encyclopedia entry, this time on an almost mythical historical figure named Johann Georg Faust. This source helps answer my research quetions involving alchemy's position in the Occult World. Both of my primary sources involve Gothe, a scholar in the 1800s, who wrote a play called Faust. This was based on this figure who not only dabbled in the demonology movement, but was also considered an alchemist.

## Das Wesen der Alchemie

Maack, Dr. Ferdinand. Das Wesen der Alchemie. Wuerttmburg, Germany. Occult Collection, Special Collections Library, Penn State University.

This is a primary source and book that was published as part of a series called the Occult World. "The Essence of Alchemy", as the English translation dictates, is a book about various aspects of alchemy. In this book many scientific notions are discussed, but are labeled as being Occult. A closer examination of this book, its description of Goethe's (the author of Faust) color theory, and the English translation of the content will hopefully reveal also what differentiates chemistry from alchemy at this point in time (the 1920s).

## Witchcraft Magic and Alchemy
    
de Givry, Grillot. Witchcraft, Magic, and Alchemy. New York, 1971. Harrisburg Library, Penn State University.

The book Witchcraft, Magic, and Alchemy is appears to be a description of various aspects of the three. This book was originally published in 1931 and will help to not only describe why alchemy is in the Occult World, but also act as a point of view into how alchemy was percieved in the 20th century. Clearly from the fact that alchemy is labeled as occult in the 20th century we are going to see differences between chemistry and alchemy, but this book should be able to answer just what those differences are with chapters like "Alchemical Material and the Operations of the Work" along with "Laboratory of the Alchemists".

## Occult and Scientific Mentalities in the Renaissance

Curry, Patrick. ""Occult and Scientific Mentalities in the Renaissance", Ed. by Brian Vickers." History of Science 23, no. 3 (Sep 01, 1985): 299. http://ezaccess.libraries.psu.edu/login?url=https://search-proquest-com.ezaccess.libraries.psu.edu/docview/1298059905?accountid=13158.

The utility of this article is clear. This article will allow us to explore the historical side of alechemy. Knowing what the mentalities are in the Renaissance will help to paint a picture of not only how alechemy may have influence chemistry of the modern scientific period, but also why alechemy may have bcome a part of the occult world. A question to ask of this text to poke at both the influence on chemistry and the appearance in the occult world is what are the similarities and differences of alchemy to both magic and chemistry?

## Alchemy and Christianity in the Middle Ages

Matus, Z. A., Alchemy and Christianity in the Middle Ages. (2012) History Compass, 10: 934-945. doi:10.1111/hic3.12013

Alchemy's connection to Christianity is similar, yet stronger than that of modern science. It may be of use in understanding how alchemy differs from modern disciplines, like chemistry, to explore this connection to the affect of religion. Many scientific minds were persecuted by religious organizations, so it would be interesting to see how the same groups viewed alchemy. This may provide a perspective on the differences between the two.

## Faust

Von Goethe, Johann Wolfgang. Faust. Minneapolis: Lerner Publishing Group, 1949. Accessed November 13, 2019. ProQuest Ebook Central.

Faust is a play written by Gothe, who is a scholar referenced in another source in this list. The play was first published in 1808 and is a look into how an alchemist (Faust) at this time was very similar to a witch, but was not persecuted. He makes a deal with the devil essentially, but is labelled as an alchemist. This play is really important for understanding alchemy's role in the occult world, and how closely it really ties in.

## The Alchemist

Lovecraft, H. P. The Alchemist. http://www.hplovecraft.com/writings/texts/fiction/a.aspx.

Part of this research topic is understanding how alchemy was viewed in the turn of the 20th century. H. P. Lovecraft wrote this short story in 1908 when he was just 17 or 18. This source will be able to provide a window into the influence of alchemy and its position in the occult on works of art, such as literature. When reading this short story it is important to not only think about how alchemy is viewed as the occult, but also how this story would be if it was titled "The Chemist" and written differently.









































